on: pull_request
name: PR
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Use Node.js 24.x
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: npm i
              run: npm ci

            - name: cache deps
              uses: actions/cache/save@v5
              with:
                  path: node_modules
                  key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
                  restore-keys: ${{ runner.os }}-

    checks:
        needs: setup
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                check: ["format:ci", "lint:ci"]
        steps:
            - uses: actions/checkout@v6

            - name: Restore deps
              uses: actions/cache/restore@v5
              with:
                  path: node_modules
                  key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

            - name: Use Node.js 24.x
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x

            - name: Run ${{ matrix.check }}
              run: npm run ${{ matrix.check }}
